### ISSUE TITLE
Lunar isnt launching

### ISSUE THREAD

**Issue by SoulFire2879** [Aetopia/Portaluna#4]
I previously made an issue and @Aetopia  closed this saying i didnt do it properly and  now i have made a complete video of me installing at and the msg box that i get once its installed and of me running it and it failing
Please watch it lol
https://anonfiles.com/L7Bbxbdfx2/y_mp4 (file is too big for github)

**Comment by Aetopia** [comment]
![image](https://user-images.githubusercontent.com/41850963/147459132-757c097c-283d-419c-a504-11bb54659586.png)
Seems that your Windows Installation has unsynchronized time.
Check your time settings and update Windows to the latest version.

**Comment by SoulFire2879** [comment]
> ![image](https://user-images.githubusercontent.com/41850963/147459132-757c097c-283d-419c-a504-11bb54659586.png) Seems that your Windows Installation has unsynchronized time. Check your time settings and update Windows to the latest version.

Well i hope thats the cause of my issues

**Comment by SoulFire2879** [comment]
![image](https://user-images.githubusercontent.com/77575770/147497885-ac5b6f3d-dbbf-4a43-806b-4e39fc52a88a.png)
ok ive synced time , do i have to do anything else?
